// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpRziGJhRa3r8oZYreUxffW4a630sIH7c',
    appId: '1:773233380314:web:350ad7c2565062b0d6cee3',
    messagingSenderId: '773233380314',
    projectId: 'mostfa-said',
    authDomain: 'mostfa-said.firebaseapp.com',
    databaseURL: 'https://mostfa-said-default-rtdb.firebaseio.com',
    storageBucket: 'mostfa-said.firebasestorage.app',
    measurementId: 'G-4MPQX98Z8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS923nE9lXPVVuvLXebIAFPx0gTTdli2o',
    appId: '1:773233380314:android:c4536cbc020eb97fd6cee3',
    messagingSenderId: '773233380314',
    projectId: 'mostfa-said',
    databaseURL: 'https://mostfa-said-default-rtdb.firebaseio.com',
    storageBucket: 'mostfa-said.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyBZoPkjvMxbMj8BJkdv7Jb8Zvbif4wUY',
    appId: '1:773233380314:ios:9639fcbffd44e669d6cee3',
    messagingSenderId: '773233380314',
    projectId: 'mostfa-said',
    databaseURL: 'https://mostfa-said-default-rtdb.firebaseio.com',
    storageBucket: 'mostfa-said.firebasestorage.app',
    iosClientId: '773233380314-cncthu6fubhguh5lc1hvpr8alrsfeaj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.appweb1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyBZoPkjvMxbMj8BJkdv7Jb8Zvbif4wUY',
    appId: '1:773233380314:ios:9639fcbffd44e669d6cee3',
    messagingSenderId: '773233380314',
    projectId: 'mostfa-said',
    databaseURL: 'https://mostfa-said-default-rtdb.firebaseio.com',
    storageBucket: 'mostfa-said.firebasestorage.app',
    iosClientId: '773233380314-cncthu6fubhguh5lc1hvpr8alrsfeaj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.appweb1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpRziGJhRa3r8oZYreUxffW4a630sIH7c',
    appId: '1:773233380314:web:b2813e48e0aa3328d6cee3',
    messagingSenderId: '773233380314',
    projectId: 'mostfa-said',
    authDomain: 'mostfa-said.firebaseapp.com',
    databaseURL: 'https://mostfa-said-default-rtdb.firebaseio.com',
    storageBucket: 'mostfa-said.firebasestorage.app',
    measurementId: 'G-MY7BT0ZYLE',
  );

}